export const Users = [
   { id:1,
    profilePicture: "assests/profile/p1.png",
    username: "Aira Sharma",
},
{ id:2,
    profilePicture: "assests/profile/p2.webp",
    username: "Shayma",
},
{ id:3,
    profilePicture: "assests/profile/p3.jpg",
    username: "Rohit Yadav",
},
{ id:4,
    profilePicture: "assests/profile/p5.jfif",
    username: "Ashish kumar",
},
{ id:5,
    profilePicture: "assests/profile/p4.webp",
    username: "Shailja Gupta",
},
{ id:6,
    profilePicture: "assests/profile/p6.jpg",
    username: "Shubhadra Yadav",
},
{ id:7,
    profilePicture: "assests/profile/p7.jpg",
    username: "Atul yadav",
},
{ id:8,
    profilePicture: "assests/profile/p8.jpg",
    username: "Tannu",
},
{ id:9,
    profilePicture: "assests/profile/p9.jpeg",
    username: "Sarita Yadav",
},
{ id:10,
    profilePicture: "assests/profile/p10.png",
    username: "Madhu Singh",
},
];

export const Posts = [
{
    id:1,
    desc:"Love for all, hatred for none",
    photo:"assests/post/n1.jfif",
    date:"32 mins ago",
    userId:1,
    like:130,
    comment:50,
},
{
    id:2,
    photo:"assests/post/n2.webp",
    date:"5 mins ago",
    userId:2,
    like:30,
    comment:9,
},
{
    id:3,
    desc:"Love youself ",
    photo:"assests/post/n3.jfif",
    date:"13 mins ago",
    userId:3,
    like:53,
    comment:15,
},
{
    id:4,
    desc:"Every moment is a fresh begining",
    photo:"assests/post/n4.jfif",
    date:"3 mins ago",
    userId:4,
    like:10,
    comment:2,
},
{
    id:5,
    // desc:"Love for all, hatred for none",
    photo:"assests/post/n5.jpg",
    date:"23 mins ago",
    userId:5,
    like:40,
    comment:10,
},
];